"""Agregando auditoria a la base de datos

Revision ID: afe62bc9678c
Revises: 8e6f8b1619a9
Create Date: 2026-09-28 11:03:24.250334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe62bc9678c'
down_revision: Union[str, Sequence[str], None] = '8e6f8b1619a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Clients',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()'),
        ),
    )
    op.add_column(
        'Clients',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()'),
        ),
    )
    op.add_column(
        'Users',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()'),
        ),
    )
    op.add_column(
        'Users',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'updated_at')
    op.drop_column('Users', 'created_at')
    op.drop_column('Clients', 'updated_at')
    op.drop_column('Clients', 'created_at')
    # ### end Alembic commands ###